# Generated by Django 4.1.1 on 2022-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.IntegerField(max_length=200, unique=True)),
                ('City', models.CharField(max_length=200, unique=True)),
                ('ContactNo', models.IntegerField(max_length=200, unique=True)),
            ],
        ),
    ]
