# Generated by Django 4.0.7 on 2022-10-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('U_Type', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='customerrecord',
            name='Status',
            field=models.CharField(default='Not Active', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='City',
            field=models.CharField(default='CITY', max_length=200),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='ContactNo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerrecord',
            name='Name',
            field=models.CharField(default='ABC', max_length=200),
        ),
    ]
